name: Compile-Windows

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build
    - uses: dtolnay/rust-toolchain@nightly
    - run: cargo build --release --verbose
    - name: Upload binary artifact
      uses: actions/upload-artifact@v3.1.1
      with:
        name: bales-win64-msvc
        path: target/release/bales.exe
    - name: Create Release
      uses: marvinpinto/action-automatic-releases@v1.2.1
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "latest"
        prerelease: true
        title: "Windows Build"
        files: |
          target/release/bales.exe
